package com.company.pmsmain.entity.enums;

public enum CountryCode {

    ABW("ABW", "ARUBA"),
    AFG("AFG", "AFGHANISTAN"),
    AGO("AGO", "ANGOLA"),
    AIA("AIA", "ANGUILLA"),
    ALA("ALA", "ALAND ISLANDS"),
    ALB("ALB", "ALBANIA"),
    AND("AND", "ANDORA"),
    ANT("ANT", "NETHERLANDS ANTILLE"),
    ARE("ARE", "UNITED ARAB EMIRATES"),
    ARG("ARG", "ARGENTINA"),
    ARM("ARM", "ARMENIA"),
    ASM("ASM", "AMERICAN SAMOA"),
    ATA("ATA", "ANTARCTICA"),
    ATF("ATF", "FRENCH SOUTHERN TERRITORIES"),
    ATG("ATG", "ANTIGUA AND BARBUDA"),
    AUS("AUS", "AUSTRALIA"),
    AUT("AUT", "AUSTRIA"),
    AZE("AZE", "AZERBAIDJAN"),
    BDI("BDI", "BURUNDI"),
    BEL("BEL", "BELGIUM"),
    BEN("BEN", "BENIN"),
    BES("BES", "BONAIRE, SINT EUSTATIUS AND SABA"),
    BFA("BFA", "BURKINA FASO"),
    BGD("BGD", "BANGLADESH"),
    BGR("BGR", "BULGARIA"),
    BHR("BHR", "BAHRAIN"),
    BHS("BHS", "BAHAMAS"),
    BIH("BIH", "BOSNIA AND HERZEGOVINA"),
    BLM("BLM", "SAINT BARTHELEMY"),
    BLR("BLR", "BELARUS"),
    BLZ("BLZ", "BELIZE"),
    BMU("BMU", "BERMUDA"),
    BOL("BOL", "BOLIVIA"),
    BRA("BRA", "BRAZIL"),
    BRB("BRB", "BARBADOS"),
    BRN("BRN", "BRUNEI DARUSSALAM"),
    BTN("BTN", "BHUTAN"),
    BVT("BVT", "BOUVET ISLAND"),
    BWA("BWA", "BOTSWANA"),
    CAF("CAF", "CENTRAL AFRICAN REPUBLIC"),
    CAN("CAN", "CANADA"),
    CCK("CCK", "COCOS ISLAND"),
    CHE("CHE", "SWITZERLAND"),
    CHL("CHL", "CHILE"),
    CHN("CHN", "CHINA"),
    CIV("CIV", "COTE D'IVOIRE"),
    CMR("CMR", "CAMEROON"),
    COD("COD", "CONGO, THE DEMOCRATIC REPUBLIC"),
    COG("COG", "CONGO"),
    COK("COK", "COOK ISLANDS"),
    COL("COL", "COLOMBIA"),
    COM("COM", "COMOROS"),
    CPV("CPV", "CABO VERDE"),
    CRI("CRI", "COSTA RICA"),
    CRM("CRM", "CRIMEA"),
    CUB("CUB", "CUBA"),
    CUW("CUW", "CURACAO"),
    CXR("CXR", "CHRISTMAS ISLANDS"),
    CYM("CYM", "CAYMAN ISLANDS"),
    CYP("CYP", "CYPRUS"),
    CZE("CZE", "CZECH REPUBLIC"),
    DEU("DEU", "GERMANY"),
    DJI("DJI", "DJIBOUTI"),
    DMA("DMA", "DOMINICA"),
    DNK("DNK", "DENMARK"),
    DOM("DOM", "DOMINICAN REPUBLIC"),
    DZA("DZA", "ALGERIA"),
    ECU("ECU", "ECUADOR"),
    EGY("EGY", "EGYPT"),
    ERI("ERI", "ERITREA"),
    ESH("ESH", "WESTERN SAHARA"),
    ESP("ESP", "SPAIN"),
    EST("EST", "ESTONIA"),
    ETH("ETH", "ETHIOPIA"),
    FIN("FIN", "FINLAND"),
    FJI("FJI", "FIJI"),
    FLK("FLK", "FALKLAND ISLANDS (MALVINAS)"),
    FRA("FRA", "FRANCE"),
    FRO("FRO", "FAEROE ISLANDS"),
    FSM("FSM", "MICRONESIA, FEDERATED STATES OF"),
    GAB("GAB", "GABON"),
    GBR("GBR", "UNITED KINGDOM"),
    GEO("GEO", "GEORGIA"),
    GGY("GGY", "GUERNSEY"),
    GHA("GHA", "GHANA"),
    GIB("GIB", "GIBRALTAR"),
    GIN("GIN", "GUINEA"),
    GLP("GLP", "GUADELOUPE"),
    GMB("GMB", "GAMBIA"),
    GNB("GNB", "GUINEA-BISSAU"),
    GNQ("GNQ", "EQUATORIAL GUINEA"),
    GRC("GRC", "GREECE"),
    GRD("GRD", "GRENADA"),
    GRL("GRL", "GREENLAND"),
    GTM("GTM", "GUATEMALA"),
    GUF("GUF", "FRENCH GUIANA"),
    GUM("GUM", "GUAM"),
    GUY("GUY", "GUYANA"),
    HKG("HKG", "HONG KONG"),
    HMD("HMD", "HEARD AND MCDONALD ISLANDS"),
    HND("HND", "HONDURAS"),
    HRV("HRV", "CROATIA"),
    HTI("HTI", "HAITI"),
    HUN("HUN", "HUNGARY"),
    IDN("IDN", "INDONESIA"),
    IMN("IMN", "ISLE OF MAN"),
    IND("IND", "INDIA"),
    IOT("IOT", "BRITISH INDIAN OCEAN TERRITORY"),
    IRL("IRL", "IRELAND"),
    IRN("IRN", "IRAN"),
    IRQ("IRQ", "IRAQ"),
    ISL("ISL", "ICELAND"),
    ISR("ISR", "ISRAEL"),
    ITA("ITA", "ITALY"),
    JAM("JAM", "JAMAICA"),
    JEY("JEY", "JERSEY (CHANNEL ISLANDS)"),
    JOR("JOR", "JORDAN"),
    JPN("JPN", "JAPAN"),
    KAZ("KAZ", "KAZAKHSTAN"),
    KEN("KEN", "KENYA"),
    KGZ("KGZ", "KYRGYZSTAN"),
    KHM("KHM", "CAMBODIA"),
    KIR("KIR", "KIRIBATI"),
    KNA("KNA", "ST.KITTS AND NEVIS"),
    KOR("KOR", "THE REPUBLIC OF KOREA"),
    KWT("KWT", "KUWAIT"),
    LAO("LAO", "LAOS"),
    LBN("LBN", "LEBANON"),
    LBR("LBR", "LIBERIA"),
    LBY("LBY", "LIBYAN ARAB JAMAHIRIYA"),
    LCA("LCA", "SAINT LUCIA"),
    LIE("LIE", "LIECHTENSTEIN"),
    LKA("LKA", "SRI LANKA"),
    LSO("LSO", "LESOTHO"),
    LTU("LTU", "LITHUANIA"),
    LUX("LUX", "LUXEMBOURG"),
    LVA("LVA", "LATVIA"),
    MAC("MAC", "MACAO"),
    MAF("MAF", "SAINT MARTIN (FRENCH PART)"),
    MAR("MAR", "MOROCCO"),
    MCO("MCO", "MONACO"),
    MDA("MDA", "MOLDOVA, REPUBLIC OF"),
    MDG("MDG", "MADAGASCAR"),
    MDV("MDV", "MALDIVES"),
    MEX("MEX", "MEXICO"),
    MHL("MHL", "MARSHALL ISLANDS"),
    MKD("MKD", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
    MLI("MLI", "MALI"),
    MLT("MLT", "MALTA"),
    MMR("MMR", "MYANMAR"),
    MNE("MNE", "MONTENEGRO"),
    MNG("MNG", "MONGOLIA"),
    MNP("MNP", "NORTHERN MARIANA ISLANDS"),
    MOZ("MOZ", "MOZAMBIQUE"),
    MRT("MRT", "MAURITANIA"),
    MSR("MSR", "MONTSERRAT"),
    MTQ("MTQ", "MARTINIQUE"),
    MUS("MUS", "MAURITIUS"),
    MWI("MWI", "MALAWI"),
    MYS("MYS", "MALAYSIA"),
    MYT("MYT", "MAYOTTE"),
    NAM("NAM", "NAMIBIA"),
    NCL("NCL", "NEW CALEDONIA"),
    NER("NER", "NIGER"),
    NFK("NFK", "NORFOLK ISLAND"),
    NGA("NGA", "NIGERIA"),
    NIC("NIC", "NICARAGUA"),
    NIU("NIU", "NIUE"),
    NLD("NLD", "NETHERLANDS"),
    NOR("NOR", "NORWAY"),
    NPL("NPL", "NEPAL"),
    NRU("NRU", "NAURU"),
    NZL("NZL", "NEW ZEALAND"),
    OMN("OMN", "OMAN"),
    PAK("PAK", "PAKISTAN"),
    PAN("PAN", "PANAMA"),
    PCN("PCN", "PITCAIRN"),
    PER("PER", "PERU"),
    PHL("PHL", "PHILIPPINES"),
    PLW("PLW", "PALAU"),
    PNG("PNG", "PAPUA NEW GUINEA"),
    POL("POL", "POLAND"),
    PRI("PRI", "PUERTO RICO"),
    PRK("PRK", "DEMOC.PEOPLES REP.OF KOREA"),
    PRT("PRT", "PORTUGAL"),
    PRY("PRY", "PARAGUAY"),
    PSE("PSE", "PALESTINIAN TERRITORY, OCCUPIED"),
    PYF("PYF", "FRENCH POLYNESIA"),
    QAT("QAT", "QATAR"),
    REU("REU", "REUNION"),
    ROU("ROU", "ROMANIA"),
    RUS("RUS", "RUSSIAN FEDERATION (USSR)"),
    RWA("RWA", "RWANDA"),
    SAU("SAU", "SAUDI ARABIA"),
    SCT("SCT", "SCOTLAND"),
    SDN("SDN", "SUDAN"),
    SEN("SEN", "SENEGAL"),
    SGP("SGP", "SINGAPORE"),
    SGS("SGS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND"),
    SHN("SHN", "ST. HELENA"),
    SJM("SJM", "SVALBARD AND JAN MAYEN ISLANDS"),
    SLB("SLB", "SOLOMON ISLANDS"),
    SLE("SLE", "SIERRA LEONE"),
    SLV("SLV", "EL SALVADOR"),
    SMR("SMR", "SAN MARINO"),
    SOM("SOM", "SOMALIA"),
    SPM("SPM", "ST. PIERRE AND MIQUELON"),
    SRB("SRB", "SERBIA & MONTENEGRO"),
    SSD("SSD", "SOUTH SUDAN"),
    STP("STP", "SAO TOME AND PRINCIPE"),
    SUR("SUR", "SURINAME"),
    SVK("SVK", "SLOVAK REPUBLIC"),
    SVN("SVN", "SLOVENIA"),
    SWE("SWE", "SWEDEN"),
    SWZ("SWZ", "ESWATINI, KINGDOM OF (SWAZILAND)"),
    SXM("SXM", "SINT MAARTEN"),
    SYC("SYC", "SEYCHELLES"),
    SYR("SYR", "SYRIAN ARAB REPUBLIC"),
    TCA("TCA", "TURKS AND CAICOS ISLANDS"),
    TCD("TCD", "CHAD"),
    TGO("TGO", "TOGO"),
    THA("THA", "THAILAND"),
    TJK("TJK", "TAJIKISTAN"),
    TKL("TKL", "TOKELAU"),
    TKM("TKM", "TURKMENISTAN"),
    TLS("TLS", "TIMOR-LESTE"),
    TON("TON", "TONGA"),
    TTO("TTO", "TRINIDAD AND TOBAGO"),
    TUN("TUN", "TUNISIA"),
    TUR("TUR", "TURKIYE"),
    TUV("TUV", "TUVALU"),
    TWN("TWN", "TAIWAN"),
    TZA("TZA", "TANZANIA UNITED REPUBLIC"),
    UGA("UGA", "UGANDA"),
    UKR("UKR", "UKRAINE"),
    UMI("UMI", "UNITED STATES MINOR OUTLYING ISLANDS"),
    URY("URY", "URUGUAY"),
    USA("USA", "UNITED STATES OF AMERICA"),
    UZB("UZB", "UZBEKISTAN"),
    VAT("VAT", "VATICAN CITY STATE (HOLY SEE)"),
    VCT("VCT", "SAINT VINCENT AND GRENADINES"),
    VEN("VEN", "VENEZUELA"),
    VGB("VGB", "VIRGIN ISLANDS(BRITISH)"),
    VIR("VIR", "VIRGIN ISLANDS(US)"),
    VNM("VNM", "VIETNAM"),
    VUT("VUT", "VANUATU"),
    WLF("WLF", "WALLIS AND FUTUNA ISLANDS"),
    WSM("WSM", "SAMOA"),
    XKX("XKX", "KOSOVO"),
    YEM("YEM", "YEMEN"),
    ZAF("ZAF", "SOUTH AFRICA"),
    ZMB("ZMB", "ZAMBIA"),
    ZWE("ZWE", "ZIMBABWE");

    private final String code;
    private final String country;

    CountryCode(String code, String country) {
        this.code    = code;
        this.country = country;
    }

    public String getCode()    { return code; }
    public String getCountry() { return country; }

    @Override
    public String toString() { return code + " – " + country; }
}