# Server
server.port=${SERVER_PORT:8100}

# Main datasource
main.datasource.url=${MAIN_DATASOURCE_URL}
main.datasource.username=${MAIN_DATASOURCE_USERNAME}
main.datasource.password=${MAIN_DATASOURCE_PASSWORD}

# Tenant liquibase
tenant.liquibase.change-log=classpath:/com/company/pmsmain/liquibase/changelog.xml

# Disable dev mode
vaadin.devmode.enable=false
vaadin.productionMode=true

# Logging
logging.level.root=WARN
logging.level.com.company.pmsmain=INFO

app.reports.path=/app/reports
tenant.db.host-override=${TENANT_DB_HOST_OVERRIDE:}
stimulsoft.license-key=6vJhGtLLLz2GNviWmUTrhSqnOItdDwjBylQzQcAOiHniybdy0GTiG5m0W2Rod6W7is+/ZFzG44BbsFIKjesRM1f6w6lujSwlu3kguOaMJPrurrWdRNGIKwF8VBYoAHUHjbdXQZCyYXQtcREfiI/ID8HcS5n3YHFN5SUJ1E8KRFbi6OqW4UoqqheNjEft510yDoDywoleOpp6P/XdL7ZCxHymRmfIxIeH8Y6dfs2c1THYghHkvxQai/7YYJZ7f5TxgOxABDfrV7bw/XVOruJM8OLCWoH4hNo28advxj8syuXDlWqpa84Ykh4TCXAEpFk3H1m+eFWatQSBapKeotTchmrwIDkgr0eLAAfo9kyw8vlLg8zPOrPZACzoQM6neqaufP5bnVOu0wJeJ8r1OGae7BaqrtArz1aCRopvK06F3cDWJElxYYwQf7ILC0X0wpsn8dpFRJFB/j92ap/vHoFtRC5jVOt9tsce/OQbOXJI3t9pdL8FnxdhMHKJb098ab+NoqJGZ6cFrk1JTQOLS4IquCLx9glVFjej+25VLoLGir0SPdDrOwItbd/TH1LmYCuI
vaadin.theme=pms-blue

# HelpDesk API endpoints (Zorin server — same host as the app)
helpdesk.chat.base-url=http://192.168.0.159:7863
helpdesk.support.base-url=http://192.168.0.159:7870
helpdesk.connect-timeout-ms=10000
helpdesk.read-timeout-ms=60000