# Server
server.port=8080

# Main datasource
main.datasource.url=${MAIN_DATASOURCE_URL}
main.datasource.username=${MAIN_DATASOURCE_USERNAME}
main.datasource.password=${MAIN_DATASOURCE_PASSWORD}

# Tenant liquibase
tenant.liquibase.change-log=classpath:/com/company/pmsmain/liquibase/changelog.xml

# Disable dev mode
vaadin.devmode.enable=false
vaadin.productionMode=true

# Logging
logging.level.root=WARN
logging.level.com.company.pmsmain=INFO